Algoritmo "exercicio 4"

// Autor(a)    :paulo henrique lima silva
// Data atual  : 25/05/2023
Var
nome:caractere
nota1,nota2,nota3,nota4:real


inicio
escreval ("digite seu nome ")
leia(nome)
escreval ("digite as notas")
leia(nota1)
leia(nota2)
leia(nota3)
leia(nota4)

se (nota1 + nota2 + nota3 + nota4) > 7 entao
escreval("",nome," foi aprovado.")
senao
escreval("",nome," foi reprovado.")
fimse







Fimalgoritmo
fimse