Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : edilma bindá
// Autor(a)    : paulo henrique lima silva
// Data atual  : 30/03/2023
Var
dolar,cotacao,reais:real


Inicio
escreval ("digite a cotação do dolar")
leia(cotacao)
escreval ("digite o valor monetarioa ser convertido em dolar")
leia(reais)
dolar <- reais / cotacao
escreval ("o dinheiro em dolar é ",dolar,".")


Fimalgoritmo