Algoritmo "semnome"
// Disciplina   : [pa]
// Professor   : edilma pindá
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : paulo henrique lima silva
// Data atual  : 09/03/2023
Var
graus,TEMPERATURA:real



iniCIO
ESCREVAL ("----------------------------------------------------------")
escreval ("DIGITE OS GRAUS")
LEIA (GRAUS)
ESCREVAL ("----------------------------------------------------------")

//PROCESSAMENTO
temperatura <- (9*graus + 160) /5
ESCREVAL ("----------------------------------------------------------")

//SAIDA
ESCREVAL ("A TEMPERATURA FICA: ", TEMPERATURA)
ESCREVAL ("-----------------------------------------------------------")





Fimalgoritmo