Algoritmo "conversao de dolar para real"
// Disciplina   : PA
// Professor   : Edilma Bindá
// Autor(a)    : paulo henrique lima silva
// Data atual  : 09/03/2023
Var
dolares, cotacao, total:real

Inicio

escreval ("Informe quantos dolares deseja converter")
leia (dolares)

escreval ("Informe a cotação atual do dolar")
leia (cotacao)

//processamento
total <- dolares/cotacao

//saida

escreval ("Resulta em ", total ," Reais ")


Fimalgoritmo